---
title: "2024년 기록"
author: "류지창"
date: "2024-03-03"
date-modified: last-modified
categories: [기록]
toc: true
# image:
---

## 2024-03-03 일
이번주 목요일이 박사논문 프로포절 리허설이다. 드디어 내 차례가 왔다. 3/21(목)에는 프로포절 발표가 있고 5월에 디펜스를 한다. 이제 손에 꼽을만큼의 날들만 남아있다. 10년전엔 상상으로만 했고 이걸 하고싶어서 악몽에 시달렸던 나인데 어느덧 내 꿈을 실현시키는 순간으로 와있다. 과거의 내가 지금의 나를 봤다면 만족했을까. 안심하고 지냈을까.
어제는 지건이의 결혼준비이야기를 듣고 할 말이 너무 많아 아주 긴 문장으로 메시지를 보냈다. 부디 동생이 잘 해내기를, 그리고 좋은 삶을 살기를 바랄뿐이다.
3월 프로포절이 끝나면 p4 논문초안으로 교수님과 미팅하고 4월초에 투고해야된다. 계획보다 2-3개월 늦어졌는데 생각보다 효율계산이 잘 되지않아서이다. 지금은 몇 가지 케이스에서는 되고, 어떤 케이스에서는 안 되는데 남은 한 달동안 이 부분을 잘 갈무리해야된다. 그리고나서 4월 말경에 p5 논문(지금 생각으로는 농축도 분석이 가장 적절할 듯하다)에 대해 교수님과 미팅하고 6월초에 투고하려고 한다. 가장 중요한 박사학위논문은 프로포절이 끝나는 3월 말부터는 쓰기 시작해야된다. 그래야 6월말 제출까지 3개월은 붙들고 계속 수정보완해나갈 수 있다.

## 2024-03-08 금
어제 박사학위 프로포절 리허설을 했다. 리허설을 위한 발표자료 준비로 거의 1주일간 매일 1시간 30분씩만 잠을 자는-그러니까 대략 새벽 5시반에 잠들어서 7시에 깸- 강행군을 했다. 그 때문에 회사에 가면 오전시간에 잠이 쏟아져서 점심시간에는 밥을 먹으러가지 못하고 책상에 엎드려 잠을 잤다. 잠이 몰려와서 도저히 밥먹으러 갈 수 없었던 경험은 처음이었다. 그래도 하얀이가 싸준 도시락 덕분에 오전시간에 도시락을 먹고 점심에 잠을 자도 그렇게 배가 고프지는 않았다.
프로포절 리허설에서는 발표가 약 30분정도 걸렸고 교수님 및 랩원들과의 피드백이 1시간가량 이어졌다. 의미있고 중요한 시간이었다. 특히 교수님은 이 발표를 좀 더 간결하고 이해하기 쉽게 만들라고 하셨다. 발표연습이 더 필요할 거라고 하셨는데 솔직히 발표에 자신이 있었던 나로서는 오랜만에 받아보는 비판이었다. 집으로 돌아오는 내내 무엇이 문제였는지 생각했다. 그리고 좀 부당하다는 생각도 들었다. "이걸 왜 제대로 이해해주시지 않는걸까." 잠이 들어서도 계속 그 생각이 이어졌고 도율이와 같이 밤 9시에 잠들어 새벽 6시에 일어나서 다시 생각을 이어갔다. 그러다 문득 이런 생각이 났다. '처음 듣는 사람들의 입장에서는 이 발표가 좋은 발표는 아니었겠구나.' 그러면서 내가 발표로 칭찬을 받았던 회사에서의 고강도 집속초음파 발표와 비판을 받았던 박사학위 리허설을 비교해보았다. 이 둘의 결정적인 차이는 욕심에 있다. 집속초음파 발표는 무엇보다 내가 개발한 것도 아니고 나는 단지 이 기술을 전달하는 입장에서 깊이있는 내용보다는 이 기술의 정당성과 효과에만 집중해서 발표했다. 그러다보니 발표자료도 각 페이지마다 핵심이 되는 그림 몇 개만으로 구성되어 있었다. 반면 박사학위 발표자료는 내가 직접 고생해서 연구한 결과를 더 풍성하게 보여주고 싶고, 멋있게 만들고 싶고, 이 내용이 어렵다는 걸 알아줬으면 하는 욕심에서 매 페이지마다 디테일을 계속 추가했다. 어제 교수님이 볼츠만 식이 있는 페이지에서 "이건 텍스트북의 요약이지 발표자료가 아닌데"라고 말씀하셨다. 이제야 그 말이 왜 타당한 비판이었는지 이해했다. 이건 발표자료가 아니다. 특히 서술식으로 쓰여있어서 청중이 발표시간동안 그 페이지를 읽을 수가 없다. 그렇구나. 이건 다 내 욕심때문에 생긴 문제였다. 
이런 생각들을 거쳐 지금은 회사 책상에 앉아있는데 돌이켜보니 어제의 리허설은 정말 값진 시간이었다. 그 시간이 아니었다면 나는 잘못된 자아도취에 빠져-나는 발표를 잘한다는 착각- 이런 불친절한 발표자료로 디펜스를 할 뻔했다. 그 결과는 보나마나 안 좋은 발표로 이어졌을 것이다. 이제 남은 2주간 발표자료의 디테일을 다 빼버리고 핵심 아이디어만을 수면 위에 띄워놓는다. 그것도 그림으로 표현할 수 있도록 대부분의 글줄을 그림설명으로 교체한다. 그리고 설명을 위해 단순화된 케이스를 만들고 이를 적절한 비유로 청중들을 이해시킨다. 그렇게 되어야 제대로된 발표가 된다. Deliver to you. 나는 이 아이디어를 "전달"하는 사람이다. 무엇을 제대로 전달하려면 중요한 것만 손에 쥐어주면 된다. 열쇠만 쥐어주면 되는거지 무거운 쇠덩어리를 들라고 전부 다 전달해서는 안된다.

## 2024-03-22 금
어제(2024-03-21) 박사학위 프로포절을 했다. 심사위원은 조규성 교수님, 장동찬 교수님, 성지현 교수님, 곽성우 박사님, 손욱 박사님으로 구성했다. 하루 휴가를 내고 카이스트 도서관에 가서 내용을 다시 정리한 다음 1시쯤에 제본을 하고 캘리포니아 베이커리 카이스트점에서 다과와 음료를 사서 유레카관으로 향했다. 3시에 조문형 박사과정이 먼저 발표했고 나는 4시부터 시작했다. 교수님께서 발표가 끝나고 나서 둘 다 잘했다고 말씀해주셨지만 그걸로는 만족이 되지 않았다. 뭔가 좀 더 발표공간을 압도하고 싶었는데 그러지 못했다는 생각이 들어 아쉬움이 계속 남았다. 프로포절이 끝나고 랩원들과 백숙집에서 회식을 했고 맞은편의 엔젤인어스 커피집에서 커피를 마시고 헤어졌다. 헤어지기 전 교수님이 오늘 과감한 시도를 했다면서 악수를 청하셨다. 나는 정말 좋은 연구를 하고 있는걸까. 조금 더 견고하고 결정적인 연구를 하고 싶다. 지금의 상태로는 만족할 수가 없다. 이제 마라톤의 마무리를 알리는 마지막 트랙에 들어섰다. 한 바퀴. 나에게 남은 이 한 바퀴를 온 힘을 다해 달려야된다. 5월말에 최종발표가 있을 예정이니 주어진 시간은 2달. 이 시간동안 스스로에게 후회가 남지 않도록 모든걸 쏟아부어야겠다. 더 치밀하고, 더 확실하게.


## 2024-06-22 토
당직실에서 숙직 중이다. 밖에는 이슬비가 내리고있다. 잠깐 밖으로 나가 비를 맞으며 본관을 둘러싼 산을 바라보았다. 어두워진 공기 사이로 은은하게 비치는 울창한 나무들이 보였다. 나에게 먹을 것을 주고 쉴 곳을 제공해준 이 산이 따뜻하게 느껴졌다. 어느 회사던지 비슷한 조건을 제공해주었겠지만 KNF만큼 완벽하게 해내지는 못했을 것이다. 이 회사덕분에 하고싶은 일을 하면서 공부도 했다. 그래서 고대하고 바라던 박사학위도 받는다. 6/14(금)에 디펜스를 마쳤고 어제 학위논문 제본을 맡겼다. 다음주 목요일에 학과사무실에 논문을 제출하면 박사학위를 위한 모든 준비가 끝난다. 박사라니. 카이스트 박사. 류지창 박사. 지금까지의 10년은 박사학위를 위해 달렸다. 앞으로의 10년은 박사로써의 의무와 책임감으로 사회에 기여하기 위해 달린다.
