---
title: "노트 정리방법"
author: "류지창"
date: "2023-09-17"
date-modified: last-modified
categories: [기록]
toc: false
# image:
---
출처: [https://sootax.co.kr/5225](https://sootax.co.kr/5225)

EBS 클래스에서 제공하는 '강유원의 책읽기와 글쓰기

## 10강 매체들과 자료정리


제가 열 번에 걸쳐서 책 읽기와 글쓰기에 관해서 강의를 한다고 말씀드렸는데 지금 열 번째 시간입니다. 지금 열 번째 시간은 책 읽기와 글쓰기에 대해서 말씀드리기보다는 책과 글에 대해서 직접적으로 관련이 것이 아닌 도구들에 대해서 말씀을 드리려고 합니다. 제가 따로 마지막 시간을 할애해서 이런 도구들을 말씀드리는 이유는 뭐냐 하면 TV나 라디오, 또는 잡지 같은 매체들에서 글스는 사람들, 작가들 또는 저자들, 학자들 인터뷰 같은 것을 많이 합니다. 그러면 그 사람들이 어떤 도구를 사용하는지 좀 판타스틱하게 보여주는 경향이 있어요. 그 연필이 부러지도록 쓴다라든가 제가 여섯 번째 시간에 제가 사용하고 있는 만년필 잠깐 보여드렸는데 그것만으로는 제대로 되지 않습니다. 그때도 말씀드린 것처럼 훌륭한 목수는 연장을 탓하지 않는다. 왜 탓하지 않느냐? 훌륭한 연장이 있기 때문에 연장을 탓하지 않습니다. 책과 관련된 매체에 대해서 이야기하겠습니다.

제가 지금은 그 서점이 없어졌는데 제가 대학을 다닐 때 종로2가에 YMCA빌딩이 있는데요, 맞은 편에 종로서적이라고 있습니다. 그때는 책 살 돈이 별로 없으니까 종로서적에 가서 책을 검색을 해보곤 했습니다. 지금은 인터넷 서점으로 저는 책을 삽니다. 그리고 인터넷 서점 중에서 주기적으로 검색을 해서 관심 도서를 살펴봅니다. 이런 것은 꼭 필요합니다. 두번째로 도서 구입하는 예산을 반드시 책정하려고 노력을 해야 합니다. 돈 남으면 책 산다 이것이 아니라 책 살 돈을 미리 따로 떼어놓고 꼭 그만큼은 사야 한다를 의무적으로, 먹고 살 돈도 없는데 책 살 돈이 어디있느냐 라고 말하시는 분이 이 강의를 보지 않으실거라고 봐요. 제가 좀 한이 맺힌 것처럼 말씀드렸는데 책 살 돈을 꼭 따로 떼어 놓자. 대부분이 그렇습니다. 인터넷 사이트에서 이렇게 포털 사이트나 블로그 같은 곳에 검색을 해보면 맛집을 찜해두는 분들이 많이 있습니다. 또 맛집을 찜해두는 앱도 나와있습니다. 그런데 맛집을 찜해두는 일에는 그렇게 열심이면서 책 살 돈을 따로 떼어놓지 않는다는 것은 정말 알 수가 없어요. 이거는 이 프로그램을 보는 분들은 그런데 관심있는 분들일테니까 제가 아주 강력하게 말씀드립니다. 만원이 되었건 2만원이 되었건 책 살 돈을 따로 떼어놓자. 그리고 자기계발서도 아닌데 제가 가끔 인문학 관련된 책들, 이런 책들에 한줄평 남긴 것들을 보면, 제 책 말고 다른 사람들 책, 이런 것을 쭉 봅니다. 그런데 책 값이 비싸다, 12,000원짜리 책에서 책 값이 비싸다 이렇게 말씀하시면 곤란해요. 또 제가 쓴 책 중에 4,000원짜리 책이 있습니다. 그 책을 사서 읽고, 2,000원 중고서점에 내놓는 건 곤란해요. 책 값이 비싸다라고 말씀하시는 경우엔 사실 저도 가끔은 속된 말로 이 책은 가성비가 너무나 떨어진다 이런 경우가 있어요. 그런데 적어도 책에 대해서는요 가성비를 말하지 않고 꾹 참는 것, 이게 교양의 출발점입니다.

세 번째. 책을 읽고나서 어떤 분들은 지금 제가 이 책을 이렇게 접는 것을 보고 아주 그냥 소스라쳐 놀라는 분들이 있어요. 책을 소중하게 다루는 분들이 있어요. 비싼 책이라고 13,000원이나 주고 샀어, 소중해 이렇게 하시는 분들이 있는데 그러지 마시고 책은 산 이상 내 것입니다. 이것을 곱게 보고 중고서점에 내놓으실 거면 모르지만 그게 아닌 한은 책을 사면 책은 찢어버리지 않은 한은 험하게 다루셔도 괜찮습니다. 그리고 책을 읽으면서 이렇게 꼭 여백에 메모하고 물질적인 흔적을 남기는게 굉장히 중요합니다. 그리고 지난 번에 제가 여섯째 시간에도 보여드렸듯이 이런 독서카드, 만년필, 이런 문방구들 또 이렇게 독서 카드를 가지고 다니는 가죽 패드 이런 거 있잖아요. 이런 것들에 대해서 관심을 갖는 것도 필요합니다. 제가 지금 지난 번에 여섯째 시간에 보여드린 만년필들이 있는데 제가 주로 글을 쓸 때 사용하는 만년필이 100만원이 넘습니다. 그리고 그 옆에 그 보조로 쓰는 만년필들이 기본적으로 한 20만원씩 합니다. 그러니까 싹 모으면 200만원은 되겠죠. 그런데 저한테 그런 얘기를 하시는 분들이 있어요. 10만원짜리 만년필도 사려면 집사람 눈치가 보입니다. 그렇게 말을 하시는 분들이 가끔 있어요. 눈치가 보이면 사지 마세요. 그런데 적어도 설득은 하셔야 돼요. 이런 것들이 필요하다. 이게 사치가 아니다. 문방구는 사치품이 아니다. 이런 설득이 필요합니다. 그러면 책도 도서관에서 빌려서 보고 그 다음에 모나미 볼펜만 가지고 이면지에다가 아무렇게나 한다고 그러면 언제 무슨 공부를 하고 서평을 쓰겠습니까. 일단은 기본적으로 투자를 해야 합니다. 그런 돈을 아까워하면 안된다 그런 얘기죠. 지금 이 프로그램을 보시는 분 중에 하루 삼시세끼 먹고 사는 것 자체가 힘든 분은 없을거라고 생각해요. 삼시세끼 먹고 사는게 힘든 분들을 경멸해서 드리는 말씀이 아니라 일단 책을 읽고 교양을 쌌겠다고 하시는 분들이 그것에 들어가는 도구들에 대해서 관심을 갖지 않는다는 것은 그냥 안 하시는 게 낫다 그런 얘기를 드리고 싶습니다.

정보 기술도 어느 정도 활용하실 필요가 있습니다. 요즘에 스마트폰들이 나오니까 스마트 기기로 뭐든지 다 할 수 있다고 생각하시는 분들이 있는데 이렇게 종이에 써서, 제가 지금 강의하는 내용도 종이에 써왔지 않습니까, 이걸 구별하는 게 필요합니다. 제 방에 책꽂이에 1990년에, 1990년이면 지금부터 30년 전입니다. 1990년에 제가 박사학위 논문을 쓰기 위해서 삼공 노트에 만년필로 노트 정리했던 것을 가지고 있습니다. 그런데 재미있는것은요, 제가 1990년에 매킨토시 클래식 투라고 하는 컴퓨터를 쓰기 시작했는데 매킨토시 클래식 투에 보관했던 디지털 파일은 가지고 있질 않아요. 그리고 그걸 읽을 수 있는 기기도 없습니다. 저는 그 누구 못지않게 최신 디지털 기기를 사용했습니다. 그런데 왜 제가 이렇게 생긴 종이에다가 글 쓸 것을 여러분들에게 말씀드리느냐. 종이에 써야 되는 것과 디지털로 처리햐야 되는 것을 구별하는 것이 정보관리의 핵심입니다. 이것은요 오랫동안 보관할 수 있어요. 오래도록 보관해야 될 것 그것은 반드시 종이에 적어서 보관해야 합니다. 그리고 종이에 써둔 것들은요, 이렇게 쭉 늘어놓고 볼 수가 있거든요. 자신이 공부하는 것에 관련되는 것들은 종이에 써서 자주 들여다보고 일람이 가능한 형태로 가지고 있을 필요가 있습니다. 그리고 낱장을 된 메모장도 필요하지만 그것들을 모아서 두는 수첩도 반드시 필요하다. 즉 디지털 기기, 정보 기기를 활용하지 말아라 라고 말씀드리는 것이 아니라 디지털 기기로 처리해야 할 것과 이렇게 종이로 손으로 써서 처리해야 될 것을 확실하게 구별하는 것이 공부하고 관련된 또는 책 읽기와 글쓰기에 관련된 정보 처리의 핵심이다. 그런 말입니다.

그 다음 저에게 독서카드를 쓰기 시작했습니다. 그런데 어떻게 분류를 하나요 이렇게 물어보는 분들이 가끔 있어요. 어떤 식으로 분류를 하고 계십니까. 이렇게 물어보는 분들이 있는데 그래서 제가 독서카드를 가지고 왔습니다. 자 여기 보면 오른쪽 상단에 피에르 부르디외라고 써있는 부분이 있습니다. 이거는 제가 독서카드를 쓸 때 키워드를 오른쪽에 씁니다. 그 다음에 피에르 부르디외라고 쓰고 여기에 이 제 이 카드의 제목을 이렇게 씁니다. 그런데 지금 이 카드들은 다 피에르 부르디외라는 상단의 키워드가 다 달려 있습니다. 그럼 이것을 제가 피에르 부르디외라고 하는 분류함을 따로 가지고 있지는 않아요. 그냥 이런것들은요 모아둡니다. 모아두고 분류를 하지는 않습니다. 그러면 어떻게 그 카드를 가령 200장을 써서 모아놨어. 그러면 그것을 어떻게 분류하십니까. 또는 어떻게 분류해서 찾아보십니까. 방법이 아주 간단합니다. 어떻게 하느냐. 틈날 때마다 카드를 꺼내서 읽습니다. 다시 말해서 색인, 인덱스는 제 머리에다가 둡니다. 이게 핵심입니다. 자신의 머리를 믿어야 된다는 것이죠. 머릿속에다가 색인을 만드십시요.

그 다음 책을 샀어요. 책을 샀는데 책은 어떻게 분류하십니까. 저는요, 일단 아무데나 꽂습니다. 그 다음에 어디에 무슨 책이 있는 것을 어떻게 아십니까. 심심할 때면 책장 앞에 서서 아 이 책이 여기에 꽂혀있구나 하고 머릿속에 기억을 합니다. 그 방법말고는 없어요. 도서관을 이용할 수 있다면 서사분들을 활용할 수 있겠지만 저는 저에게 개인 보조 사서가 없기 때문에 저 혼자 이 책이 여기 있구나 저 책이 저기 있구나. 그런데 못찾으면 분명히 예전에 인터넷 서점에서 데이터베이스를 검색해보면 책을 산 것으로 나와요. 그런데 책을 제방에서 못찾는다. 그런데 급해. 그 책을 꼭 보고 싶어. 독서카드에다가도 정리를 안해놓은 것 같아. 그럴 때는 어떻게 하느냐. 그냥 다시 한번 삽니다. 그 방법 밖에 없어요. 다시 말해서 책은 저자를 중심으로 꽂기도 하고 그다음에 주제 중심으로 꽂기도 하고 구입 순서대로 꽂기도 합니다. 핵심은 뭐냐. 자주 들여다봐서 어디에 무슨 책이 꽂혀 있는지를 머릿 속에 정리해 두는 것이 필요하다.

그 다음에 마지막으로 말씀드릴 것은 뭐냐면 제가 첫 시간에도 말씀드렸나 그런 것 같아요. 책을 읽은 다음에는 반드시 이 면지를 활용해서 책의 내용을 독서카드를 쓰지 않는 책들은 면지에다가 간략하게라도 적자. 그래서 심심할 때 아주 책이나 끄집어 내서 아 이 책은 내가 3년 전에 사서 읽었구나 하고 면지에 있는 내용을 이렇게 들여다보면서 그 기억을 되살리는 게 좋습니다. 그런데 그 책을 내가 한 3,4년 전에 읽었는데 도대체 기억이 나지 않아. 어떻게 하면 좋아. 그럴 때는 어쩔 수 없어요. 인간은 그렇게 해서 잊어버릴 수가 있습니다. 그게 가장 좋습니다. 그리고 마지막으로 드리고 싶은 말은 뭐냐. 책 보다도 더 소중한 것은 사람이기 때문에 책에 지나치게 매몰되서 인생을 망가뜨리지는 마시라는 것입니다.

지금까지 열 번에 걸쳐서 책 읽기와 글쓰기에 대해서 말씀드렸는데요, 한가지 정리해서 딱 한마디를 드리면 책은 내 삶을 풍요롭게 해주는 도구에 불과하다. 책 자체에 지나치게 몰두해서 인생을 망가뜨리지는 말아야 한다. 그러나 적절한 수준으로 책에 몰두하고 또 그것을 정리하고 공책에 쓰고 독서카드에 정리하고 글로 써보는 것, 이것보다도 더 인생을 풍요롭게 해주는 것은 없다. 이게 제가 지금까지 30~40년 가까이 책 읽고 글을 쓰면서 얻게 된 교훈입니다. 지금까지 열 번에 걸쳐서 제 강의를 시청해주셔서 고맙습니다.
