---
title: "2023년 기록"
author: "류지창"
date: "2023-09-24"
date-modified: last-modified
categories: [기록]
toc: true
# image:
---

## 2023-09-24 일
quarto를 이용한 웹사이트 정비를 완료했다. 이제 댓글기능까지 가능하기 때문에 웹사이트로서의 기능을 온전히 할 수 있다. 매일의 전진을 여기에 조금씩 기록하자. 나의 목적은 오로지 어제보다 나은 내가 되는 것이다. 그걸 위해 사용가능한 모든 도구를 쓴다. 이 사이트도 그런 의미에서 활용된다.


## 2023-09-28 목
추석연휴라 대구에와서 쉬는 중이다. 오늘은 할아버지 산소에 갔다가 부모님이 만든 오두막(컨테이너)에서 등목을 하고 좀 쉬다가 왔다. 오는 길에는 삼성현에 있는 카페에서 빙수를 먹었고 NC 백화점 5층에서 도율이와 생태체험관에서 즐거운 시간을 보냈다. 도율이가 4살이 되어 예전보다 훨씬 부드러운 생활을 할 수 있어서 좋다.


## 2023-10-30 월
p3_ 논문쓰는 중이다. 한 문장 나아가는게 고되고 힘들다. 문장이 완성되는걸 보는 후련함이 있지만 그 과정은 결코 쉽지 않네. 


## 2023-11-01 수
도율이가 밤새 열이나서 오전반차를 쓰고 같이 있었다. 아침에 잠깐 눈떳을때 어제 받은 약을 먹이고 사과 한 입과 젤리 3개를 먹였다. 그러고는 다시 잠들었는데 11시정도까지 잠을 잤다. 약 2시반 30분정도 잔 셈. 다행히 자고 일어났을 땐 열이 37도로 떨어졌다.
장인어른이 오셔서 나는 11시 45분경에 회사로 출발했고 지금은 오후 2시 12분인데 p3_ 논문의 result 부분까지 얼추 썼다. method에서 수식정리하고 기호들 정리하는 작업이 필요하다. 오늘 퇴근전까지 discussion을 다 쓰는게 목표.
그러고 나면 오늘 밤에 method와 result를 정리하고 내일 회사에서 conclustion을 다듬으려고 한다. 일반 여기까지 되면 영문교정을 신청할 수 있으니 내일 오전 중에 영문교정을 보내고 익일교정으로 신청하면 다음날인 11/3(금)에 교정된 논문을 받을 수 있다. 그걸 바탕으로 주말동안 그림과 표 정리, 그리고 문장 가다듬기에 공을 들이면 다음주 월요일인 11/6(월)에 투고 가능하다. 11/5(일) 저녁에 교수님께 투고 전 확인메일을 보내면 되겠다.
투고 후에는 p4_ 폴더를 만들고 새로운 논문(박사학위논문을 위한 마지막 퍼즐)을 위한 준비작업을 한다. 남은 11월에는 p4_ 결과를 보는 것에 온 힘을 집중한다.


## 2023-11-07 화
어제부로 p3_ 논문을 완성하고 카이스트 영문교정센터에 교정을 의뢰했다. 오늘 오전에는 교수님께 cover letter와 논문 본문을 보내고 투고 전 확인요청을 드렸다. 교수님 회신이 오면(오늘 밤 아니면 내일쯤 오지 않을까) 투고한다. 이번에는 투고저널로 Nucl. Instrum. Methods Phys. Res. A를 선택했다. 항상 한 번쯤 투고해보고 싶었던 곳이기도 하고 저널랭킹을 보다보니 다른 곳보다는 Q1에 해당하는 여기를 먼저 시도해보는게 좋겠다는 생각이 들었다. 만약 거절당하면 다음 대안은 IEEE TNS이다.
논문을 탈고하니 속이 후련하다. 머리가 가벼워진 느낌이다. 이제 p4_ 연구를 새로 시작하는데 내가 좋아하는 시점이 바로 처음 연구를 시작할 때와 연구결과가 나올 때이다. 지금이 바로 시작하는 시점이니 기분이 좋다. p3_를 보완하고 확장시켜서 p4_를 제대로 만들어보자. 내 박사과정의 종착역이 될 논문이니까 결과 하나하나에 더 공을 들여서 만들려고 한다.

## 2023-11-08 수
카이스트 영문교정의뢰한 파일의 작업이 완료되었다는 메일을 아침에 받고 회사에 와서 열어보았다. 교정작업을 한 외국인의 작업시간이 오전 5시 30분쯤으로 나와있어서 정말 일찍일어나서 일을 했구나라는 생각을 했다. 교정된 파일은 대부분 관사에서 지적을 받았는데 The와 A의 사용이 부적절했고 on을 regarding으로 바꾸고 hence를 thus로 바꾸는 등 문장을 전치사와 부사 수준에서 디테일하게 수정하는 작업이 주를 이루었다. 역시 영작은 하기에는 어려운데 막상 좋은 문장을 보면 깔끔하고 깊은 맛이 딱 느껴진다. 좋은 문장을 쓰고싶다.
어제 교수님께 보낸 메일을 읽긴 하셨는데 아직 답장이 없다. 오늘 중에 답장이 오면 퇴근 후에 제출하고 싶은데.. 답장을 기다려보자.

## 2023-12-03 일
지금 딱 12시 1분이 되어 내 생일이 됐다. 장평 시골에서 김장을 하고 오후 6시 50분부터 서동사우나에서 목욕을 개운하게 한 뒤 시골집으로 돌아와 노트북을 켰다. 몇 일전부터 Flax 결과가 잘 안나와서 고심했는데 일단 그럴듯한 결과를 만드는데 까지는 성공했다. 이제 PyTorch와 완전히 같은 결과를 확인한 후에 numpyro로 넘어갈 수 있다.
어제 저녁을 먹고 시골로 왔는데 시골에 오면 전기장판에서 따뜻하게 잘 수 있어서 좋다. 또 오늘은 오랜만에 목욕도 해서 기분이 좋았다. 도율이는 하얀이와 같이 여탕에서 씻고 왔는데 혹시나 안 씻겠다고 울고 나올까봐 걱정했는데 왠걸 1시간이 넘게 정말 잘 씻고 나왔다. 하얀이에게 물어보니 온탕에서 수영도 하고 탕 안에서 계속 잘 놀았다고 한다. 도율이가 어딜가든 잘 지내서 같이 여행다닐 맛이 난다. 고마워 도율아!
2017년도에 내가 쓴 일기가 생각난다. 12월 3일이 되고 자취방에서 저녁에 홀로 지내다 문득 큰 외로움을 느꼈다. 그래서 일기에 나의 사회생활에 대한 반성같은 걸 적었다. 그리고 이틀 뒤였나 같은 부서에 근무하던 하얀이에게 잠깐 시간이 있냐고 해서 회의실로 들어가 요즘 슬럼프라고 말했다. 그냥 하얀이에게 그런 말을 하고 싶었다. 아마 그 때 여자친구를 사귀고 싶은 갈망이 컸던 것 같다. 그러고는 몇 주 뒤 하얀이와 어반자카파 공연을 보러 갔고 그리고 2달 뒤인 2018년 2월부터 하얀이를 사겨 지금 여기에 있다.
남은 생을 하얀이, 도율이와 같이 즐겁게 살아야지.

아참, 그리고 오늘 오전에 엄마에게서 전화가 왔다. 생일 축하한다고 하셨고 내 아들로 태어나줘서 고맙다고 하셨다. 언제나 엄마를 생각하면 좋다. 나도 엄마 아들이어서 좋다. 몇 번이고 다시 태어나더라도 엄마의 아들이고 싶다.
