---
title: "Log"
author: "류지창"
date: "2023-09-01"
# data-modified: "2023-09-02"
categories: [thoughts]
# image:
# toc: false
---

## 2023-05-09 화
내가 보니 아래 분야만 제대로 이해하고 있어도 논문을 읽거나 새로운 이론을 전개하는데 무리없다.

- 수리통계
- 선형대수
- 해석학
- 학률론 및 측도론
- 수치해석
- 미적분
- 푸리에급수
- 특수함수에 대한 이해(e.g. 삼각함수, 베셀함수 등)

이 외의 수학은 있으면 더 좋고 없으면 아쉽지만 그래도 학자로서 먹고사는데는 지장이 없는 수준이다. 고로 위의 7가지를 하나씩 격파해나가는걸 학자의 자존심을 걸고 수행해야 된다. 우선 첫 번째는 가장 시급하다고 느끼는 수리통계부터 하자. 교과서는 얼추 모아놨는데 온라인 강의로 큐스터디를 병행한다. 지금부터 수강하면 올해 연말에 끝나고 그 다음 해에는 확률론과 측도론, 그리고 선형대수와 해석학으로 들어간다. 동시에 미적분은 온라인 강의없이 혼자서 독학-이정도는 혼자 해도 되잖아-한다. 2년 뒤에-38살- 수치해석과 푸리에급수, 특수함수 등에 대해 공부한다.


## 2023-07-10 월 (20:34)
[dfm](https://dfm.io/) 이사람을 보고 오픈소스를 다루는 법을 배우자. 자기에게 필요한 것을 스스로 만들어 보충해서 쓰는데 코드 작성에 대해 좋은 감각을 가지고 있다. 유용한 코드도 많이 만들었다. 심지어 더 마음에 드는 점은 전문 프로그래머가 아니라 천문학자이면서 코드를 쓰는 사람이라는 점이다. 자기 전문분야가 있으면서 그 분야에 필요한 코드를 만드는 것. 이 정도 능력이면 내가 앞으로 먹고 사는데 지장없을거다. 앞으로 3년간 읽고 쓰며 배우자.
[rougier](ttps://www.labri.fr/perso/nrougier/) 시각화에 관해선 이 사람을 보고 배운다. 엄청난 작업량과 코딩능력이다. 과학기술분야의 탑이 아닐까?
http://gbaydin.github.io/ 미분가능한 시뮬레이션 개발에는 이 사람의 작업물을 참고한다. 이 정도의 그룹을 이끌면 학자로서 성공한 거 아닐까?


## 2023-09-02 토
공부를 해야지. 그러려면 우선순위가 필요하다. 알지만 실천이 잘 안된다. 박사졸업까지 이제 10개월이 채 안남았다. 고전물리, 수학에 대한 일반적인 관심은 남은 기간동안만이라도 참고 내려놓자. 그정도는 할 수 있잖아? 공부라는 이름으로 정당화하지마라. 언젠가 필요할거라는 정당화도 안된다. 그냥 하지 않아야된다.